### ISSUE TITLE
 java.nio.file.NoSuchFileException: ..\data\filmtrust\rating

### ISSUE THREAD

**Issue by hsingyang** [guoguibing/librec#119]
i have import librec-core in pom.xml, but when i run the main function ,it occurs:
Exception in thread "main" net.librec.common.LibrecException: java.nio.file.NoSuchFileException: ..\data\filmtrust\rating
	at net.librec.data.model.TextDataModel.buildConvert(TextDataModel.java:75)
	at net.librec.data.model.AbstractDataModel.buildDataModel(AbstractDataModel.java:139)
	at com.cmbchina.ccd.Controller.RecommendList.main(RecommendList.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.nio.file.NoSuchFileException: ..\data\filmtrust\rating

how can i resolve this

**Comment by allenjack** [comment]
Hi,
It means you did not correctly set the path of the data directory. I suggest that you can try to change the 'dfs.data.dir' to './data'. And you can run the program step by step and then check whether the data path is correct or not.

**Comment by hsingyang** [comment]
i can change the "dfs.data.dir" in which file?

**Comment by hsingyang** [comment]
when i debug my code ,i find that i have load the userknn-test.properties , and i copy the "data" file into my program , but i am not sure i put it in the right  location , could you tell me the right location for "data\filmtrust\rating"?

**Comment by hsingyang** [comment]
when i debug my code ,i find that i have load the userknn-test.properties and i copy the "data" file into my program . i am not sure  i put "data" file in the right location , i have tested many locations but "NoSuchFileException " still happens 
could you tell me the right location for "data\filmtrust\rating"?

**Comment by allenjack** [comment]
If you still have the problem, you can specify the absolute data path. Basically, you have to know where you put your data files.

**Comment by shenmeolo** [comment]
I meet the same problem. This is my code ：
 Configuration conf = new Configuration();
        conf.set("dfs.data.dir", "D:/ratings.txt");

Exception in thread "main" net.librec.common.LibrecException: java.nio.file.NoSuchFileException: D:\ratings.txt\filmtrust\rating

The ratings.txt  which I put it under the D disk. I am sure i put the file in the right location.
 How to modify the code.

**Comment by shenmeolo** [comment]
I solve the problem.
if you put ratings.txt under the D disk,you should create D:\data\filmtrust\rating. then you put ratings.txt under the  D:\filmtrust\rating.  So  the absolute data path is D:\data\filmtrust\rating\ratings.txt .
But the code should be write like this:
        Configuration conf = new Configuration();
        conf.set("dfs.data.dir", "D:\data");
