### ISSUE TITLE
How to run a TrustSVDTestCase with my dataset

### ISSUE THREAD

**Issue by xiexiaomiao** [guoguibing/librec#142]
I change the librec.properties :
dfs.data.dir=../data
dfs.result.dir=../result
data.input.path=mydataset

**Comment by hdi-amiri** [comment]
so what is the problem? what is the error?

**Comment by xiexiaomiao** [comment]
but it still use filmtrust dataset not my dataset

Dataset: ../data/filmtrust/rating
TextDataConvertor: All dataset files [..\data\filmtrust\rating\ratings_0.txt, ..\data\filmtrust\rating\ratings_1.txt, ..\data\filmtrust\rating\ratings_2.txt, ..\data\filmtrust\rating\ratings_3.txt]
TextDataConvertor: All dataset files size 411942
TextDataConvertor: Now loading dataset file ratings_0
TextDataConvertor: Now loading dataset file ratings_1
TextDataConvertor: Now loading dataset file ratings_2
TextDataConvertor: Now loading dataset file ratings_3

**Comment by hdi-amiri** [comment]
How you have used the config file? via `Resource`? use the following code:

        Configuration conf = new Configuration();

        Properties prop = new Properties();
        InputStream input = null;

        try {
            input = new FileInputStream("conf/yourconfig.properties");
            prop.load(input);
        } catch (IOException e) {
            e.printStackTrace();
        }


        for (String name : prop.stringPropertyNames()) {
            conf.set(name, prop.getProperty(name));
        }


        RecommenderJob job = new RecommenderJob(conf);
        job.runJob();

**Comment by xiexiaomiao** [comment]
what's this

`17/05/28 16:22:24 INFO TextDataConvertor: Dataset: ../data/mydataset
Exception in thread "main" net.librec.common.LibrecException: java.nio.file.NoSuchFileException: ..\data\mydataset
	at net.librec.data.model.TextDataModel.buildConvert(TextDataModel.java:75)
	at net.librec.data.model.AbstractDataModel.buildDataModel(AbstractDataModel.java:139)
	at net.librec.job.RecommenderJob.generateDataModel(RecommenderJob.java:163)
	at net.librec.job.RecommenderJob.executeRecommenderJob(RecommenderJob.java:140)
	at net.librec.job.RecommenderJob.runJob(RecommenderJob.java:122)
	at mypackage.MyTest.main(MyTest.java:38)
Caused by: java.nio.file.NoSuchFileException: ..\data\mydataset
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at net.librec.data.convertor.TextDataConvertor.readData(TextDataConvertor.java:201)
	at net.librec.data.convertor.TextDataConvertor.processData(TextDataConvertor.java:156)
	at net.librec.data.model.TextDataModel.buildConvert(TextDataModel.java:73)
	... 5 more
`

**Comment by hdi-amiri** [comment]
it cannot find your dataset ! the path the you have set is wrong, I suggest you to use absolute path instead of relative path

**Comment by xiexiaomiao** [comment]
`17/05/28 19:14:38 INFO TextDataConvertor: Dataset: C:/Users/dell/Desktop/filmtrust/
17/05/28 19:14:38 INFO TextDataConvertor: All dataset files [C:\Users\dell\Desktop\filmtrust\ratings.txt, C:\Users\dell\Desktop\filmtrust\trust.txt]
17/05/28 19:14:38 INFO TextDataConvertor: All dataset files size 396056
17/05/28 19:14:38 INFO TextDataConvertor: Now loading dataset file ratings
17/05/28 19:14:38 INFO TextDataConvertor: Now loading dataset file trust
17/05/28 19:14:38 INFO TextDataModel: Transform data to Convertor successfully!
17/05/28 19:14:38 INFO TextDataModel: Split data to train Set and test Set successfully!
17/05/28 19:14:38 INFO TextDataModel: Data size of training is 29889
17/05/28 19:14:38 INFO TextDataModel: Data size of testing is 7423
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at net.librec.util.ReflectionUtil.newInstance(ReflectionUtil.java:72)
	at net.librec.util.ReflectionUtil.newInstance(ReflectionUtil.java:55)
	at net.librec.job.RecommenderJob.executeRecommenderJob(RecommenderJob.java:143)
	at net.librec.job.RecommenderJob.runJob(RecommenderJob.java:122)
	at mypackage.MyTest.main(MyTest.java:38)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at net.librec.util.ReflectionUtil.newInstance(ReflectionUtil.java:64)
	... 4 more
`

**Comment by hdi-amiri** [comment]
I guess that you have set `rec.recommender.class` wrong, use some other values like: `pmf` or `socialmf`

**Comment by xiexiaomiao** [comment]
Yes，you are right .So if I want to use TrustSVD,how should I set rec.recommender.class 's value

**Comment by hdi-amiri** [comment]
There is somewhere in documentation that has listed value for all algorithms, for TrustSVD you can use `trustsvd` I guess.
https://www.librec.net/dokuwiki/doku.php?id=AlgorithmList

**Comment by xiexiaomiao** [comment]
`17/05/28 20:52:17 INFO TextDataConvertor: Now loading dataset file trust
17/05/28 20:52:17 INFO TextDataModel: Transform data to Convertor successfully!
17/05/28 20:52:17 INFO TextDataModel: Split data to train Set and test Set successfully!
17/05/28 20:52:17 INFO TextDataModel: Data size of training is 29889
17/05/28 20:52:17 INFO TextDataModel: Data size of testing is 7423
Exception in thread "main" java.lang.NullPointerException
	at net.librec.recommender.SocialRecommender.setup(SocialRecommender.java:46)
	at net.librec.recommender.context.rating.TrustSVDRecommender.setup(TrustSVDRecommender.java:92)
	at net.librec.recommender.AbstractRecommender.recommend(AbstractRecommender.java:216)
	at net.librec.job.RecommenderJob.executeRecommenderJob(RecommenderJob.java:144)
	at net.librec.job.RecommenderJob.runJob(RecommenderJob.java:122)
	at mypackage.MyTest.main(MyTest.java:38)
`

**Comment by hdi-amiri** [comment]
You are missing some important parameters for this algorithm, check sample
config file for trustsvd in wiki page

**Comment by xiexiaomiao** [comment]
parameters is:
`data.appender.class=social
data.appender.path=

rec.recommender.class=trustsvd
rec.iterator.learnrate=0.01
rec.iterator.learnrate.maximum=0.01
rec.iterator.maximum=50
rec.user.regularization=0.01
rec.item.regularization=0.01
rec.social.regularization=0.01
rec.bias.regularization=0.01
rec.factor.number=10
rec.learnrate.bolddriver=false
rec.learnrate.decay=1.0
rec.recommender.earlystop=false
rec.recommender.verbose=true
`

then
`Exception in thread "main" java.lang.NullPointerException
	at net.librec.recommender.context.rating.TrustSVDRecommender.setup(TrustSVDRecommender.java:119)
	at net.librec.recommender.AbstractRecommender.recommend(AbstractRecommender.java:216)
	at net.librec.job.RecommenderJob.executeRecommenderJob(RecommenderJob.java:144)
	at net.librec.job.RecommenderJob.runJob(RecommenderJob.java:122)
	at mypackage.MyTest.main(MyTest.java:36)`

**Comment by hdi-amiri** [comment]
what is the name of your social data? `data.appender.path=` should not be empty and should be the name of your social data which is in directory of your rating data.

**Comment by xiexiaomiao** [comment]
The problem is solved！Thank you very much！
