### ISSUE TITLE
Question about GC overhead limit exceeded.

### ISSUE THREAD

**Issue by free-qc** [guoguibing/librec#148]
Hi, Librec throws an java.lang.OutOfMemoryError at run time, this is the running log:

17/06/05 19:53:55 INFO TextDataConvertor: Dataset: ...src-v2.0/data/st/train/train.txt
17/06/05 19:53:55 INFO TextDataConvertor: All dataset files [/Users/free_qc/workspace/java/librec-librec-src-v2.0/data/st/train/train.txt]
17/06/05 19:53:55 INFO TextDataConvertor: All dataset files size 5972618
17/06/05 19:53:55 INFO TextDataConvertor: Now loading dataset file train
17/06/05 19:53:58 INFO TextDataModel: Transform data to Convertor successfully!
17/06/05 19:53:58 INFO TextDataModel: Split data to train Set and test Set successfully!
17/06/05 19:53:58 INFO TextDataModel: Data size of training is 407042
17/06/05 19:53:58 INFO TextDataModel: Data size of testing is 45315
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(HashMap.java:1742)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at net.librec.similarity.JaccardSimilarity.getCorrelation(JaccardSimilarity.java:49)
	at net.librec.similarity.AbstractRecommenderSimilarity.buildSimilarityMatrix(AbstractRecommenderSimilarity.java:89)

I found that the process of Librec took up about 2GB memory, so I set the -Xmx4g, and it didn't work. Is the train data too much?

**Comment by free-qc** [comment]
This is the usage of memory, is there a memory leak?

JVM version is 25.121-b13
using thread-local object allocation.
Parallel GC with 4 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 0
   MaxHeapFreeRatio         = 100
   MaxHeapSize              = 2147483648 (2048.0MB)
   NewSize                  = 44564480 (42.5MB)
   MaxNewSize               = 715653120 (682.5MB)
   OldSize                  = 89653248 (85.5MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 21807104 (20.796875MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 0 (0.0MB)

Heap Usage:
PS Young Generation
Eden Space:
   capacity = 401080320 (382.5MB)
   used     = 220557104 (210.3396453857422MB)
   free     = 180523216 (172.1603546142578MB)
   54.99075696359273% used
From Space:
   capacity = 90701824 (86.5MB)
   used     = 0 (0.0MB)
   free     = 90701824 (86.5MB)
   0.0% used
To Space:
   capacity = 154140672 (147.0MB)
   used     = 0 (0.0MB)
   free     = 154140672 (147.0MB)
   0.0% used
PS Old Generation
   capacity = 1431830528 (1365.5MB)
   used     = 1431830168 (1365.499656677246MB)
   free     = 360 (3.4332275390625E-4MB)
   99.99997485735966% used

 jmap -histo

 num     #instances         #bytes  class name

   1:      20446538      654289216  java.util.HashMap$Node
   2:      20415816      489979584  java.lang.Double
   3:      16694225      267107600  java.lang.Integer
   4:         29714      121191384  [Ljava.util.HashMap$Node;
