### ISSUE TITLE
problem with TrustSVD algorithm

### ISSUE THREAD

**Issue by xiexiaomiao** [guoguibing/librec#150]
i run trustsvd with douban dataset .then i get this
`Exception in thread "main" net.librec.common.LibrecException: Loss = NaN or Infinity: current settings does not fit the recommender! Change the settings and try again!
	at net.librec.recommender.AbstractRecommender.isConverged(AbstractRecommender.java:471)
	at net.librec.recommender.context.rating.TrustSVDRecommender.trainModel(TrustSVDRecommender.java:306)
	at net.librec.recommender.AbstractRecommender.recommend(AbstractRecommender.java:218)
	at net.librec.job.RecommenderJob.executeRecommenderJob(RecommenderJob.java:144)
	at net.librec.job.RecommenderJob.runJob(RecommenderJob.java:122)
	at net.librec.recommender.Mytest.main(Mytest.java:38)`

**Comment by hdi-amiri** [comment]
You must set the parameters from the corresponding paper

**Comment by guoguibing** [comment]
Try to tune the parameters, especially the learning rate.

**Comment by xiexiaomiao** [comment]
i set the parameters：
`rec.recommender.class=trustsvd
rec.iterator.learnrate=0.005
rec.iterator.learnrate.maximum=-1
rec.iterator.maximum=100
rec.user.regularization=1.2
rec.item.regularization=1.2
rec.social.regularization=0.9
rec.bias.regularization=1.2
rec.factor.number=10
rec.learnrate.bolddriver=false
rec.learnrate.decay=1.0
rec.recommender.earlystop=false
rec.recommender.verbose=true`
and i also have try learnrate = 0.01，0.05，0.1，0.5

**Comment by xiexiaomiao** [comment]
The problem is solved, thanks
