### ISSUE TITLE
Installing LibRec on a server machine

### ISSUE THREAD

**Issue by pcy1302** [guoguibing/librec#17]
Hi

I want to install LibRec on my server machine without using Eclipse. (I don't have GUI)

Is it possible? I tried to install using "javac LibRec.java" without success.

FYI, I am trying this because I want to test with Netflix dataset for which you do not provide results.

I installed maven and tried to build librec as follows

mvn compile
mvn package
java -cp target/librec-1.2.jar librec.main.LibRec

then, I got the following error...

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Table
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Table
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

Any idea how to execute librec without eclipse?

Thanks

**Comment by yfwz100** [comment]
Have you package the dependencies(eg. Google Guava)? By default, maven doesn't do this for you.

**Comment by guoguibing** [comment]
maven will do so if you compile the source code, but will not if you
directly deploy the jar package.

On 3/3/16, Wang Zhi <notifications@github.com> wrote:
> Have you package the dependencies(eg. Google Guava)? By default, maven
> doesn't do this for you.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/guoguibing/librec/issues/17#issuecomment-191319129


-- 
Best Regards,
Guibing GUO
