### ISSUE TITLE
Error occured when loading douban dataset

### ISSUE THREAD

**Issue by wuzy361** [guoguibing/librec#170]
This problem did not occur in librec1.3. and Other data sets do not have this problem.
The info below:
17/06/21 13:24:21 INFO TextDataConvertor: Dataset: D:/data_set/douban/uir.txt
17/06/21 13:24:21 INFO TextDataConvertor: All dataset files [D:\data_set\douban\uir.txt]
17/06/21 13:24:21 INFO TextDataConvertor: All dataset files size 233085124
17/06/21 13:24:21 INFO TextDataConvertor: Now loading dataset file uir
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at net.librec.data.convertor.TextDataConvertor.readData(TextDataConvertor.java:244)
	at net.librec.data.convertor.TextDataConvertor.processData(TextDataConvertor.java:156)
	at net.librec.data.model.TextDataModel.buildConvert(TextDataModel.java:73)
	at net.librec.data.model.AbstractDataModel.buildDataModel(AbstractDataModel.java:139)
	at net.librec.tool.driver.run_main.main(run_main.java:25)

**Comment by guoguibing** [comment]
It's hard to tell if we don't have your dataset to test.

**Comment by ChenSuL** [comment]
Where can I download the douban dataset ？Could you share a link？
I find the download link in page [https://www.librec.net/datasets.html](url) has failed
@wuzy361 @guoguibing
