### ISSUE TITLE
TrustMF, dataAppender not working

### ISSUE THREAD

**Issue by fily1212** [guoguibing/librec#288]
Hi, 
I have a problem with the library 3.0.0. 
I want to use TrustMF in a subset of Yelp dataset. 
I have tried starting [this tutorial](https://www.librec.net/dokuwiki/doku.php?id=introduction ) but I have problem with DataAppender. 
This is the main I have used.
```

public class MainTest {

    public static void main(String[] args) throws Exception {

        // build data model
        Configuration conf = new Configuration();
        conf.set("dfs.data.dir", "/home/fily1212/universita/Lavoro_Yelp/librec-3.0.0/data");
        conf.set("data.input.path","yelp");
        TextDataModel dataModel = new TextDataModel(conf);
        dataModel.buildDataModel();

        // build recommender context

        conf.set("data.appender.class","social");
        conf.set("data.appender.path", "yelp/trust");
        conf.set("rec.recommender.class","trustmf");
        conf.set("rec.iterator.learnrate","0.01");
        conf.set("rec.iterator.learnrate.maximum","0.01");
        conf.set("rec.iterator.maximum","30");
        conf.set("rec.user.regularization","0.01");
        conf.set("rec.item.regularization","0.01");
        conf.set("rec.social.regularization","0.01");
        conf.set("rec.factor.number","10");
        conf.set("rec.learnrate.bolddriver","false");
        conf.set("rec.learnrate.decay","1.0");
        conf.set("rec.recommender.earlystop","false");
        conf.set("rec.recommender.verbose","true");
        conf.set("rec.social.model","T");


        String inputPath = conf.get("dfs.data.dir") + "/" + conf.get("data.input.path");
        TextDataConvertor textDataConvertor = new TextDataConvertor(inputPath);
        textDataConvertor.processData();
        SocialDataAppender dataAppender = new SocialDataAppender(conf);
        dataAppender.setUserMappingData(textDataConvertor.getUserIds());
        dataAppender.processData();


        RecommenderContext context = new RecommenderContext(conf, dataModel);


        // build similarity
        conf.set("rec.recommender.similarity.key" ,"user");
        conf.setBoolean("rec.recommender.isranking", true);
        conf.setInt("rec.similarity.shrinkage", 10);
        RecommenderSimilarity similarity = new CosineSimilarity();
        similarity.buildSimilarityMatrix(dataModel);
        context.setSimilarity(similarity);

        // build recommender
        conf.set("rec.neighbors.knn.number", "200");
        Recommender recommender = new TrustMFRecommender();
        recommender.setContext(context);

        // run recommender algorithm
        recommender.train(context);

        // evaluate the recommended result
        EvalContext evalContext = new EvalContext(conf, recommender, dataModel.getTestDataSet(), context.getSimilarity().getSimilarityMatrix(), context.getSimilarities());
        RecommenderEvaluator ndcgEvaluator = new NormalizedDCGEvaluator();
        ndcgEvaluator.setTopN(10);
        double ndcgValue = ndcgEvaluator.evaluate(evalContext);
        System.out.println("ndcg:" + ndcgValue);



    }
}
```
but I have this output: 
```

18/12/19 15:22:31 INFO TextDataConvertor: Dataset: [/home/fily1212/universita/Lavoro_Yelp/librec-3.0.0/data/yelp]
18/12/19 15:22:31 INFO TextDataConvertor: DataSet: ...rec-3.0.0/data/yelp/trust/trust.txt is finished
18/12/19 15:22:31 INFO TextDataConvertor: DataSet: ...c-3.0.0/data/yelp/rating/rating.txt is finished
18/12/19 15:22:31 INFO TextDataConvertor: rating Scale: [1.0, 2.0, 3.0, 4.0, 5.0]
18/12/19 15:22:31 INFO TextDataConvertor: user number: 884,	 item number is: 1171
18/12/19 15:22:31 INFO TextDataModel: Transform data to Convertor successfully!
18/12/19 15:22:31 INFO TextDataModel: Split data to train Set and test Set successfully!
18/12/19 15:22:31 INFO TextDataModel: Data cardinality of training is 974
18/12/19 15:22:31 INFO TextDataModel: Data cardinality of testing is 228
18/12/19 15:22:31 INFO TextDataConvertor: Dataset: [/home/fily1212/universita/Lavoro_Yelp/librec-3.0.0/data/yelp]
18/12/19 15:22:31 INFO TextDataConvertor: DataSet: ...rec-3.0.0/data/yelp/trust/trust.txt is finished
18/12/19 15:22:31 INFO TextDataConvertor: DataSet: ...c-3.0.0/data/yelp/rating/rating.txt is finished
18/12/19 15:22:31 INFO TextDataConvertor: rating Scale: [1.0, 2.0, 3.0, 4.0, 5.0]
18/12/19 15:22:31 INFO TextDataConvertor: user number: 884,	 item number is: 1171
Exception in thread "main" java.lang.NullPointerException
	at net.librec.data.convertor.appender.SocialDataAppender.readData(SocialDataAppender.java:150)
	at net.librec.data.convertor.appender.SocialDataAppender.processData(SocialDataAppender.java:99)
	at net.librec.MainTest.main(MainTest.java:53)
```
Inspecting the part of code which throws the exception (taken from [here](https://www.librec.net/dokuwiki/doku.php?id=datamodel#appender))
```
      String inputPath = conf.get("dfs.data.dir") + "/" + conf.get("data.input.path");
        TextDataConvertor textDataConvertor = new TextDataConvertor(inputPath);
        textDataConvertor.processData();
        SocialDataAppender dataAppender = new SocialDataAppender(conf);
        dataAppender.setUserMappingData(textDataConvertor.getUserIds());
        dataAppender.processData();

```
I have noticed that `textDataConvertor.getUserIds()` isn't defined in `TextDataConvertor`. 
`dataAppender` in the previous link is not defined, but I have came to the conclusion that `dataFeatrue` in the link was `dataAppender` (maybe it was a typo).
Futhermore the `userIds` in `textDataConvertor` is null and this cause the exception. 
How can I fix it and run a basic TrustMF execution? 
Thanks a lot. 
Filippo

**Comment by SunYatong** [comment]
It would be much more convenient to run with the RecommenderJob and configuration file, instead of coding the whole process of reading data, training and evaluating.

Please check the testcase of TrustMF.

**Comment by fily1212** [comment]
Hi 
Thanks a lot for your reply. 


 I created the test class that I attach:

`/**
 * Copyright (C) 2016 LibRec
 *
 * This file is part of LibRec.
 * LibRec is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LibRec is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LibRec. If not, see <http://www.gnu.org/licenses/>.
 */
package net.librec.recommender.context.rating;

import net.librec.BaseTestCase;
import net.librec.common.LibrecException;
import net.librec.conf.Configuration;
import net.librec.job.RecommenderJob;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;

/**
 * TrustMF TestCase corresponds to TrustMF Recommender
 * {@link net.librec.recommender.context.rating.TrustMFRecommender}
 *
 * @author SunYatong
 */
public class TrustMFTestCase extends BaseTestCase {

    @Before
    public void setUp() throws Exception {
        super.setUp();
    }

    /**
     * Test the whole process of TrustMF Recommender
     *
     * @throws ClassNotFoundException
     * @throws LibrecException
     * @throws IOException
     */
    @Test
    public void testRecommender() throws ClassNotFoundException, LibrecException, IOException {
        Configuration.Resource resource = new Configuration.Resource("rec/context/rating/trustmf-yelp.properties");
        conf.addResource(resource);
        RecommenderJob job = new RecommenderJob(conf);
        job.runJob();
    }
}
`


 I'm able to run it using intelljidea but now I need to run it on a server machine where I can just use the command line. I downloaded the following files for JUnit (hamcrest-core-2.1.jar, junit-4.13-beta-1.jar) and I put them in the same folder where the test class is. I tried to run it from the folder where the test class is located (/core/src/test/java/net/librec/recommender/context/rating/) using the following command javac -cp "junit-4.13-beta-1.jar:hamcrest-core-2.1.jar" TrustMFTestCase.java. But I'm obtaining the following errors: 


```
TrustMFTestCase.java:20: error: cannot find symbol
import net.librec.BaseTestCase;
                 ^
  symbol:   class BaseTestCase
  location: package net.librec
TrustMFTestCase.java:21: error: package net.librec.common does not exist
import net.librec.common.LibrecException;
                        ^
TrustMFTestCase.java:22: error: package net.librec.conf does not exist
import net.librec.conf.Configuration;
                      ^
TrustMFTestCase.java:23: error: package net.librec.job does not exist
import net.librec.job.RecommenderJob;
                     ^
TrustMFTestCase.java:35: error: cannot find symbol
public class TrustMFTestCase extends BaseTestCase {
                                     ^
  symbol: class BaseTestCase
TrustMFTestCase.java:50: error: cannot find symbol
    public void testRecommender() throws ClassNotFoundException, LibrecException, IOException {
                                                                 ^
  symbol:   class LibrecException
  location: class TrustMFTestCase
TrustMFTestCase.java:39: error: cannot find symbol
        super.setUp();
        ^
  symbol:   variable super
  location: class TrustMFTestCase
TrustMFTestCase.java:51: error: package Configuration does not exist
        Configuration.Resource resource = new Configuration.Resource("rec/context/rating/trustmf-yelp.properties");
                     ^
TrustMFTestCase.java:51: error: package Configuration does not exist
        Configuration.Resource resource = new Configuration.Resource("rec/context/rating/trustmf-yelp.properties");
                                                           ^
TrustMFTestCase.java:52: error: cannot find symbol
        conf.addResource(resource);
        ^
  symbol:   variable conf
  location: class TrustMFTestCase
TrustMFTestCase.java:53: error: cannot find symbol
        RecommenderJob job = new RecommenderJob(conf);
        ^
  symbol:   class RecommenderJob
  location: class TrustMFTestCase
TrustMFTestCase.java:53: error: cannot find symbol
        RecommenderJob job = new RecommenderJob(conf);
                                 ^
  symbol:   class RecommenderJob
  location: class TrustMFTestCase
TrustMFTestCase.java:53: error: cannot find symbol
        RecommenderJob job = new RecommenderJob(conf);
                                                ^
  symbol:   variable conf
  location: class TrustMFTestCase
13 errors

```
I can run all with IntelliJ but I can't run with terminal and I don't know why. 
Please help me! 
Thanks again.
