### ISSUE TITLE
Alpha 2.0 KCVDataSplitter

### ISSUE THREAD

**Issue by rburke2233** [guoguibing/librec#71]
Attempting to use the KCVDataSplitter (data.model.splitter=kcv) generates a run-time error.

Exception in thread "main" java.lang.RuntimeException: java.lang.NoSuchMethodException: net.librec.data.splitter.KCVDataSplitter.<init>()
	at net.librec.util.ReflectionUtil.newInstance(ReflectionUtil.java:72)
	at net.librec.util.ReflectionUtil.newInstance(ReflectionUtil.java:55)
	at net.librec.data.model.TextDataModel.buildDataModel(TextDataModel.java:61)
	at net.librec.job.RecommenderJob.executeRecommenderJob(RecommenderJob.java:134)
	at net.librec.job.RecommenderJob.runJob(RecommenderJob.java:108)

It seems that this functionality is not implemented. I realize many parts of the system are like this. It would be helpful if these non-functional classes were commented out in the driver.classes.props file. That would be a good indicator of the current state of the various components.

**Comment by wangyufengkevin** [comment]
The error has been fixed in 2.0.0-RC version, please checkout on 2.0.0-RC version. We published 2.0.0-RC version at the end of 2016, please try it, thanks.
