### ISSUE TITLE
Can't run PITFTestCase

### ISSUE THREAD

**Issue by 8-chems** [guoguibing/librec#73]
java.lang.IllegalArgumentException: Illegal max user index: -1
at net.librec.recommender.item.RecommendedItemList.<init>(RecommendedItemList.java:79)
at net.librec.recommender.TensorRecommender.recommendRating(TensorRecommender.java:292)
at net.librec.recommender.TensorRecommender.recommend(TensorRecommender.java:266)
at net.librec.recommender.TensorRecommender.recommend(TensorRecommender.java:243)
at net.librec.job.RecommenderJob.executeRecommenderJob(RecommenderJob.java:140)
at net.librec.job.RecommenderJob.runJob(RecommenderJob.java:118)
at net.librec.recommender.context.rating.PITFTestCase.testRecommender(PITFTestCase.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by guoguibing** [comment]
I think PITF is not ready for use in the current version. It will be rolled back in the final version.
